// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimulateurPret.Api.Donnees;

#nullable disable

namespace SimulateurPret.Api.Migrations
{
    [DbContext(typeof(SimulateurPretDbContext))]
    partial class SimulateurPretDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimulateurPret.Api.Modeles.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CoutTotal")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DureeMois")
                        .HasColumnType("integer");

                    b.Property<decimal>("InteretsTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Mensualite")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Montant")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TauxAnnuel")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Simulations");
                });
#pragma warning restore 612, 618
        }
    }
}
